### ISSUE TITLE
TypeError: hyperprovclient.StoreDataFS(...).then is not a function

### ISSUE THREAD

**Issue by juanoboy** [Tunstad/Hyperprov#19]
Armed with the new <a href="https://www.raspberrypi.org/blog/8gb-raspberry-pi-4-on-sale-now-at-75/">Raspberry Pi 4, 8GB</a>, and the new beta Raspberry Pi OS 64 bit, I try to employ your setup for the Hyperledger Fabric.  
Installed:
go:1.11.1, npm:6.4.1, node:v8.15.0, docker:19.03.12, docker-compose:1.21.1

After all the instructions have been followed,
using the docker logs -f <ContainerID> show nice behavior for orderer and peers.

So, I have cloned the Hyperprov.git in the  '/data' directory.
In order for DataStore.js to find the module 'hyperprov-client',
line command 'npm i hyperprov-client' is done in '/data/Hyperprov/client'
"Input.jpg" is provided, line command 'node DataStore.js' provides the message:

pi@rb27:/data/Hyperprov/client $ node DataStore.js
[2020-08-10T13:20:45.164] [INFO] Hyperprov - FileStore present and succesfully init
/data/Hyperprov/client/DataStore.js:20
    hyperprovclient.StoreDataFS(fileobj, "mycarimage").then((res) => {
^ [this arrow is under t in .then above, my comment]

TypeError: hyperprovclient.StoreDataFS(...).then is not a function
    at Object.<anonymous> (/data/Hyperprov/client/DataStore.js:20:56)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
pi@rb27:/data/Hyperprov/client $ 

I can not find a solution to this, any hints anyone?
regards John Breiland

**Comment by hhp2020** [comment]
same here i have the same issue with running this part

thanks

**Comment by markusranda** [comment]
I'm also experiencing this issue, will this ever get fixed? I'm almost starting to believe that this developer doesn't care about it's users..

**Comment by hhp2020** [comment]
have you able to run this repo on Desktop? 
i was tryig to run this repo and modify it to be able to run on desktop. but it was not successful 
do you have any recommendations?
